### ISSUE TITLE
[req] Toggle for including BBCode

### ISSUE THREAD

**Issue by ccondrup** [antimatter15/drag2up#5]
Thanks for a great addon, been using Firefox-version for some time now.
One wish: An option for wrapping the returned url in BBCode. So if I toggle BBCode on in the addon, whenever I upload an image, the textarea is filled with
    [img]http://min.us/1234[/img]

Edit: Sorry, I just noticed it already does this on some textareas, but not all. Specifically, the quick-reply field on my SMF 1.x forum never gets the BBCode added automatically.. any special reason why?
HTML for the quick reply field (which does not get BBCode):
    <textarea tabindex="1" name="message" style="width: 95%; height: 100px;" rows="7" cols="75"></textarea>

HTML for regular reply (which does get BBCode):
    <textarea tabindex="2" onchange="storeCaret(this);" onkeyup="storeCaret(this);" onclick="storeCaret(this);" onselect="storeCaret(this);" cols="60" rows="12" name="message" class="editor"></textarea>

**Comment by antimatter15** [comment]
The BBCode links occur for images on webpages whose source code includes references to bbcode, like the if string [img] is present there.

**Comment by ccondrup** [comment]
That seems fairly logical and was the info I needed, I'll make the necessary changes. Thanks!

**Comment by antimatter15** [comment]
The latest version on the trunk has a slightly broader bbcode test, and should work on some more forums that support bbcode. However, it was added just after the release of 2.2 and I don't feel like making another release with such a minor update.
